CREATE DATABASE [FX2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FX2_DemoA', FILENAME = N'C:\MSSQL\Data\FX2_DemoA.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'FX2_DemoA_log', FILENAME = N'C:\MSSQL\Data\FX2_DemoA_log.ldf' , SIZE = 2048KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FX2] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [FX2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FX2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FX2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FX2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FX2] SET ARITHABORT OFF 
GO
ALTER DATABASE [FX2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FX2] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [FX2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FX2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FX2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FX2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FX2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FX2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FX2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FX2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FX2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FX2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FX2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FX2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FX2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FX2] SET  READ_WRITE 
GO
ALTER DATABASE [FX2] SET RECOVERY FULL 
GO
ALTER DATABASE [FX2] SET  MULTI_USER 
GO
ALTER DATABASE [FX2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FX2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [FX2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [FX2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
