//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFx_Form.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Connection_買い {
            get {
                return ((string)(this["Connection_買い"]));
            }
            set {
                this["Connection_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Connection_売り {
            get {
                return ((string)(this["Connection_売り"]));
            }
            set {
                this["Connection_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Username_買い {
            get {
                return ((string)(this["Username_買い"]));
            }
            set {
                this["Username_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Username_売り {
            get {
                return ((string)(this["Username_売り"]));
            }
            set {
                this["Username_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Password_買い {
            get {
                return ((string)(this["Password_買い"]));
            }
            set {
                this["Password_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Password_売り {
            get {
                return ((string)(this["Password_売り"]));
            }
            set {
                this["Password_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 下値限界Rate_買い {
            get {
                return ((string)(this["下値限界Rate_買い"]));
            }
            set {
                this["下値限界Rate_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 下値限界Rate_売り {
            get {
                return ((string)(this["下値限界Rate_売り"]));
            }
            set {
                this["下値限界Rate_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 高値限界Rate_買い {
            get {
                return ((string)(this["高値限界Rate_買い"]));
            }
            set {
                this["高値限界Rate_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 高値限界Rate_売り {
            get {
                return ((string)(this["高値限界Rate_売り"]));
            }
            set {
                this["高値限界Rate_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 取引間隔_買い {
            get {
                return ((string)(this["取引間隔_買い"]));
            }
            set {
                this["取引間隔_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 取引間隔_売り {
            get {
                return ((string)(this["取引間隔_売り"]));
            }
            set {
                this["取引間隔_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtリミット_買い {
            get {
                return ((string)(this["txtリミット_買い"]));
            }
            set {
                this["txtリミット_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtリミット_売り {
            get {
                return ((string)(this["txtリミット_売り"]));
            }
            set {
                this["txtリミット_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txt取引単位_買い {
            get {
                return ((string)(this["txt取引単位_買い"]));
            }
            set {
                this["txt取引単位_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txt取引単位_売り {
            get {
                return ((string)(this["txt取引単位_売り"]));
            }
            set {
                this["txt取引単位_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeInterval_買い {
            get {
                return ((string)(this["TimeInterval_買い"]));
            }
            set {
                this["TimeInterval_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeInterval_売り {
            get {
                return ((string)(this["TimeInterval_売り"]));
            }
            set {
                this["TimeInterval_売り"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 更新Rate幅_買い {
            get {
                return ((string)(this["更新Rate幅_買い"]));
            }
            set {
                this["更新Rate幅_買い"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 更新Rate幅_売り {
            get {
                return ((string)(this["更新Rate幅_売り"]));
            }
            set {
                this["更新Rate幅_売り"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=1111.5;Initial Catalog=FX_DemoA;User ID=sa;Password=1111")]
        public string FXConnectionString {
            get {
                return ((string)(this["FXConnectionString"]));
            }
        }
    }
}
