USE DemoA_FX
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1_K2] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1_K2_29] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)
INCLUDE ([売りWMAs14角度]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin5_11_883534231__K1_K2] ON [hstr].[tMin5]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin1_11_851534117__K1_K2] ON [hstr].[tMin1]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_dta_index_tSec_11_819534003__K1_K2_4] ON [hstr].[tSec]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)
INCLUDE ([買いRate]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO


CREATE STATISTICS [_dta_stat_915534345_2_1_29] ON [hstr].[tMin15]([StartDate], [通貨ペアNo], [売りWMAs14角度])
GO
CREATE STATISTICS [_dta_stat_915534345_29_1] ON [hstr].[tMin15]([売りWMAs14角度], [通貨ペアNo])
GO
CREATE STATISTICS [_dta_stat_915534345_14_1_2] ON [hstr].[tMin15]([買いWMAs14角度], [通貨ペアNo], [StartDate])
GO
CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1_K2_K14] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC,
	[買いWMAs14角度] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1_K2_K29] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC,
	[売りWMAs14角度] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1_K2_K29_14] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC,
	[売りWMAs14角度] ASC
)
INCLUDE ([買いWMAs14角度]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
