USE DemoA_FX
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin15_11_915534345__K1] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tDay1_11_3531096__K1_K2] ON [hstr].[tDay1]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tHour1_11_947534459__K1] ON [hstr].[tHour1]
(
	[通貨ペアNo] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tMonth1_11_67531324__K1] ON [hstr].[tMonth1]
(
	[通貨ペアNo] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_tWeek1_11_35531210__K1_K2] ON [hstr].[tWeek1]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
