USE OANDA_DemoB
GO

CREATE NONCLUSTERED INDEX [_dta_index_tMin15_7_915534345__K1_K2_K14_29] ON [hstr].[tMin15]
(
	[通貨ペアNo] ASC,
	[StartDate] ASC,
	[買いWMAs14角度] ASC
)
INCLUDE ( 	[売りWMAs14角度]) 
WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
go
