UPDATE [RealA_FX].[hstr].tWeek1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX_ACV].[hstr].tWeek1 as b
WHERE [RealA_FX].[hstr].tWeek1.[通貨ペアNo] = b.[通貨ペアNo] AND [RealA_FX].[hstr].tWeek1.[StartDate] = b.[StartDate]
go

INSERT INTO [RealA_FX].[hstr].tWeek1
      ([通貨ペアNo]
      ,[StartDate]
      ,[買いSwap]
      ,[買いRate_始値]
      ,[買いRate_高値]
      ,[買いRate_安値]
      ,[買いRate_終値]
      ,[買いWMAs2]
      ,[買いWMAs2角度]
      ,[買いWMAs2角度シグマ]
      ,[買いWMAs2角度持続時間]
      ,[買いWMAs2角度持続Rate]
      ,[買いWMAs14]
      ,[買いWMAs14角度]
      ,[買いWMAs14角度シグマ]
      ,[買いWMAs14角度持続時間]
      ,[買いWMAs14角度持続Rate]
      ,[売りSwap]
      ,[売りRate_始値]
      ,[売りRate_高値]
      ,[売りRate_安値]
      ,[売りRate_終値]
      ,[売りWMAs2]
      ,[売りWMAs2角度]
      ,[売りWMAs2角度シグマ]
      ,[売りWMAs2角度持続時間]
      ,[売りWMAs2角度持続Rate]
      ,[売りWMAs14]
      ,[売りWMAs14角度]
      ,[売りWMAs14角度シグマ]
      ,[売りWMAs14角度持続時間]
      ,[売りWMAs14角度持続Rate]
      ,[登録日時]
      ,[更新日時])
SELECT [通貨ペアNo]
      ,[StartDate]
      ,[買いSwap]
      ,[買いRate_始値]
      ,[買いRate_高値]
      ,[買いRate_安値]
      ,[買いRate_終値]
      ,[買いWMAs2]
      ,[買いWMAs2角度]
      ,[買いWMAs2角度シグマ]
      ,[買いWMAs2角度持続時間]
      ,[買いWMAs2角度持続Rate]
      ,[買いWMAs14]
      ,[買いWMAs14角度]
      ,[買いWMAs14角度シグマ]
      ,[買いWMAs14角度持続時間]
      ,[買いWMAs14角度持続Rate]
      ,[売りSwap]
      ,[売りRate_始値]
      ,[売りRate_高値]
      ,[売りRate_安値]
      ,[売りRate_終値]
      ,[売りWMAs2]
      ,[売りWMAs2角度]
      ,[売りWMAs2角度シグマ]
      ,[売りWMAs2角度持続時間]
      ,[売りWMAs2角度持続Rate]
      ,[売りWMAs14]
      ,[売りWMAs14角度]
      ,[売りWMAs14角度シグマ]
      ,[売りWMAs14角度持続時間]
      ,[売りWMAs14角度持続Rate]
      ,[登録日時]
      ,[更新日時]
FROM [RealA_FX_ACV].[hstr].tWeek1 as b
where not exists 
(
	SELECT *
	FROM [RealA_FX].[hstr].tWeek1 as a
	where (a.[通貨ペアNo] = b.[通貨ペアNo] and a.[StartDate] = b.[StartDate])
)
go

/*
UPDATE [RealA_FX].[hstr].tMonth1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX_ACV].[hstr].tMonth1 as b
WHERE [RealA_FX].[hstr].tMonth1.[通貨ペアNo] = b.[通貨ペアNo] AND [RealA_FX].[hstr].tMonth1.[StartDate] = b.[StartDate]
go
INSERT INTO [RealA_FX].[hstr].tMonth1
      ([通貨ペアNo]
      ,[StartDate]
      ,[買いSwap]
      ,[買いRate_始値]
      ,[買いRate_高値]
      ,[買いRate_安値]
      ,[買いRate_終値]
      ,[買いWMAs2]
      ,[買いWMAs2角度]
      ,[買いWMAs2角度シグマ]
      ,[買いWMAs2角度持続時間]
      ,[買いWMAs2角度持続Rate]
      ,[買いWMAs14]
      ,[買いWMAs14角度]
      ,[買いWMAs14角度シグマ]
      ,[買いWMAs14角度持続時間]
      ,[買いWMAs14角度持続Rate]
      ,[売りSwap]
      ,[売りRate_始値]
      ,[売りRate_高値]
      ,[売りRate_安値]
      ,[売りRate_終値]
      ,[売りWMAs2]
      ,[売りWMAs2角度]
      ,[売りWMAs2角度シグマ]
      ,[売りWMAs2角度持続時間]
      ,[売りWMAs2角度持続Rate]
      ,[売りWMAs14]
      ,[売りWMAs14角度]
      ,[売りWMAs14角度シグマ]
      ,[売りWMAs14角度持続時間]
      ,[売りWMAs14角度持続Rate]
      ,[登録日時]
      ,[更新日時])
SELECT [通貨ペアNo]
      ,[StartDate]
      ,[買いSwap]
      ,[買いRate_始値]
      ,[買いRate_高値]
      ,[買いRate_安値]
      ,[買いRate_終値]
      ,[買いWMAs2]
      ,[買いWMAs2角度]
      ,[買いWMAs2角度シグマ]
      ,[買いWMAs2角度持続時間]
      ,[買いWMAs2角度持続Rate]
      ,[買いWMAs14]
      ,[買いWMAs14角度]
      ,[買いWMAs14角度シグマ]
      ,[買いWMAs14角度持続時間]
      ,[買いWMAs14角度持続Rate]
      ,[売りSwap]
      ,[売りRate_始値]
      ,[売りRate_高値]
      ,[売りRate_安値]
      ,[売りRate_終値]
      ,[売りWMAs2]
      ,[売りWMAs2角度]
      ,[売りWMAs2角度シグマ]
      ,[売りWMAs2角度持続時間]
      ,[売りWMAs2角度持続Rate]
      ,[売りWMAs14]
      ,[売りWMAs14角度]
      ,[売りWMAs14角度シグマ]
      ,[売りWMAs14角度持続時間]
      ,[売りWMAs14角度持続Rate]
      ,[登録日時]
      ,[更新日時]
FROM [RealA_FX_ACV].[hstr].tMonth1 as b
where not exists 
(
	SELECT *
	FROM [RealA_FX].[hstr].tMonth1 as a
	where (a.[通貨ペアNo] = b.[通貨ペアNo] and a.[StartDate] = b.[StartDate])
)
go

*/
