INSERT INTO [RealA_FX_ACV].[hstr].tWeek1
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[Rate_始値_買い]
      ,[Rate_高値_買い]
      ,[Rate_安値_買い]
      ,[Rate_終値_買い]
      ,[Rate_始値_売り]
      ,[Rate_高値_売り]
      ,[Rate_安値_売り]
      ,[Rate_終値_売り]
  FROM [RealA_FX_ACV_old].[fxcm].T_Rate_Weekly
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].tWeek1)

/*
INSERT INTO [RealA_FX_ACV].[hstr].[tMin15]
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[Rate_始値_買い]
      ,[Rate_高値_買い]
      ,[Rate_安値_買い]
      ,[Rate_終値_買い]
      ,[Rate_始値_売り]
      ,[Rate_高値_売り]
      ,[Rate_安値_売り]
      ,[Rate_終値_売り]
  FROM [RealA_FX_ACV_old].[fxcm].[T_Rate_15m]
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].[tMin15])

INSERT INTO [RealA_FX_ACV].[hstr].tWeek1
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].T_RateHistory_Weekly
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].tWeek1)

INSERT INTO [RealA_FX_ACV].[hstr].tMonth1
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].T_RateHistory_Monthly
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].tMonth1)

INSERT INTO [RealA_FX_ACV].[hstr].tHour1
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].T_RateHistory_Hourly
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].tHour1)

INSERT INTO [RealA_FX_ACV].[hstr].tDay1
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].[T_RateHistory_Daily]
  where [日時] < (select MIN([StartDate]) from [RealA_FX_ACV].[hstr].tDay1)
order by [日時]




INSERT INTO [RealA_FX_ACV].[hstr].tHour6
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].[T_RateHistory_6h]


INSERT INTO [RealA_FX_ACV].[hstr].[tMin30]
           ([通貨ペアNo]
           ,[StartDate]
           ,[買いRate_始値]
           ,[買いRate_高値]
           ,[買いRate_安値]
           ,[買いRate_終値]
           ,[売りRate_始値]
           ,[売りRate_高値]
           ,[売りRate_安値]
           ,[売りRate_終値])
SELECT [通貨ペアNo]
      ,[日時]
      ,[買い_始値]
      ,[買い_高値]
      ,[買い_安値]
      ,[買い_終値]
      ,[売り_始値]
      ,[売り_高値]
      ,[売り_安値]
      ,[売り_終値]
  FROM [RealA_FX_ACV_old].[dbo].[T_RateHistory_30m]
*/
