

INSERT INTO RealB_2370741683_FX_ACV.[dbo].[T_Trades]
           ([TradeID]
           ,[AccountID]
           ,[AccountName]
           ,[OfferID]
           ,[Instrument]
           ,[Lot]
           ,[AmountK]
           ,[BS]
           ,[Open]
           ,[Close]
           ,[Stop]
           ,[UntTrlMove]
           ,[Limit]
           ,[UntTrlMoveLimit]
           ,[PL]
           ,[GrossPL]
           ,[Com]
           ,[Int]
           ,[Time]
           ,[IsBuy]
           ,[Kind]
           ,[QuoteID]
           ,[OpenOrderID]
           ,[OpenOrderReqID]
           ,[QTXT]
           ,[StopOrderID]
           ,[LimitOrderID]
           ,[TradeIDOrigin])
SELECT [TradeID]
      ,[AccountID]
      ,[AccountName]
      ,[OfferID]
      ,[Instrument]
      ,[Lot]
      ,[AmountK]
      ,[BS]
      ,[Open]
      ,[Close]
      ,[Stop]
      ,[UntTrlMove]
      ,[Limit]
      ,[UntTrlMoveLimit]
      ,[PL]
      ,[GrossPL]
      ,[Com]
      ,[Int]
      ,[Time]
      ,[IsBuy]
      ,[Kind]
      ,[QuoteID]
      ,[OpenOrderID]
      ,[OpenOrderReqID]
      ,[QTXT]
      ,[StopOrderID]
      ,[LimitOrderID]
      ,[TradeIDOrigin]
  FROM RealB_2370741683_FX_ACV_old.[dbo].[T_Trades]
  where [TradeID] not in (select [TradeID] from RealB_2370741683_FX_ACV.[dbo].[T_Trades])


/*

INSERT INTO [RealA_FX_ACV].[dbo].[T_ClosedTrades]
           ([TradeID]
           ,[AccountID]
           ,[AccountName]
           ,[OfferID]
           ,[Instrument]
           ,[Lot]
           ,[AmountK]
           ,[BS]
           ,[Open]
           ,[Close]
           ,[PL]
           ,[GrossPL]
           ,[Com]
           ,[Int]
           ,[OpenTime]
           ,[CloseTime]
           ,[Kind]
           ,[OpenOrderID]
           ,[OpenOrderReqID]
           ,[CloseOrderID]
           ,[CloseOrderReqID]
           ,[OQTXT]
           ,[CQTXT]
           ,[TradeIDOrigin]
           ,[TradeIDRemain])
SELECT [TradeID]
      ,[AccountID]
      ,[AccountName]
      ,[OfferID]
      ,[Instrument]
      ,[Lot]
      ,[AmountK]
      ,[BS]
      ,[Open]
      ,[Close]
      ,[PL]
      ,[GrossPL]
      ,[Com]
      ,[Int]
      ,[OpenTime]
      ,[CloseTime]
      ,[Kind]
      ,[OpenOrderID]
      ,[OpenOrderReqID]
      ,[CloseOrderID]
      ,[CloseOrderReqID]
      ,[OQTXT]
      ,[CQTXT]
      ,[TradeIDOrigin]
      ,[TradeIDRemain]
  FROM [RealA_FX_ACV_old].[dbo].[T_ClosedTrades]
  where [TradeID] not in (select [TradeID] from [RealA_FX_ACV].[dbo].[T_ClosedTrades])

INSERT INTO [RealB_2370741683_FX_ACV].[dbo].[T_AccountsHistory]
([“úŽž]
      ,[AccountID]
      ,[AccountName]
      ,[Balance]
      ,[Equity]
      ,[DayPL]
      ,[NontrdEqty]
      ,[M2MEquity]
      ,[UsedMargin]
      ,[UsableMargin]
      ,[GrossPL]
      ,[Kind]
      ,[MarginCall]
      ,[IsUnderMarginCall]
      ,[Hedging]
      ,[AmountLimit]
      ,[BaseUnitSize])
SELECT [“úŽž]
      ,[AccountID]
      ,[AccountName]
      ,[Balance]
      ,[Equity]
      ,[DayPL]
      ,[NontrdEqty]
      ,[M2MEquity]
      ,[UsedMargin]
      ,[UsableMargin]
      ,[GrossPL]
      ,[Kind]
      ,[MarginCall]
      ,[IsUnderMarginCall]
      ,[Hedging]
      ,[AmountLimit]
      ,[BaseUnitSize]
  FROM [RealB_2370741683_FX_ACV_old].[dbo].[T_AccountsHistory]
  where [“úŽž] not in (select [“úŽž] from [RealB_2370741683_FX_ACV].[dbo].[T_AccountsHistory])

INSERT INTO [RealB_2370741683_FX_ACV].[dbo].[T_ClosedTrades]
           ([TradeID]
           ,[AccountID]
           ,[AccountName]
           ,[OfferID]
           ,[Instrument]
           ,[Lot]
           ,[AmountK]
           ,[BS]
           ,[Open]
           ,[Close]
           ,[PL]
           ,[GrossPL]
           ,[Com]
           ,[Int]
           ,[OpenTime]
           ,[CloseTime]
           ,[Kind]
           ,[OpenOrderID]
           ,[OpenOrderReqID]
           ,[CloseOrderID]
           ,[CloseOrderReqID]
           ,[OQTXT]
           ,[CQTXT]
           ,[TradeIDOrigin]
           ,[TradeIDRemain])
SELECT [TradeID]
      ,[AccountID]
      ,[AccountName]
      ,[OfferID]
      ,[Instrument]
      ,[Lot]
      ,[AmountK]
      ,[BS]
      ,[Open]
      ,[Close]
      ,[PL]
      ,[GrossPL]
      ,[Com]
      ,[Int]
      ,[OpenTime]
      ,[CloseTime]
      ,[Kind]
      ,[OpenOrderID]
      ,[OpenOrderReqID]
      ,[CloseOrderID]
      ,[CloseOrderReqID]
      ,[OQTXT]
      ,[CQTXT]
      ,[TradeIDOrigin]
      ,[TradeIDRemain]
  FROM [RealB_2370741683_FX_ACV_old].[acv].[T_ClosedTrades_Past]
  where [TradeID] not in (select [TradeID] from [RealB_2370741683_FX_ACV].[dbo].[T_ClosedTrades])
*/
