

CREATE NONCLUSTERED INDEX [_dta_index_T_RateHistory_5_5575058__K1_K2_3] ON [dbo].[T_RateHistory]
(
	[’Ê‰ÝƒyƒA] ASC,
	[Date] ASC
)
INCLUDE ( 	[Rate_”ƒ‚¢]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
