USE [FX_DemoA]
GO

SET ANSI_PADDING ON
go
CREATE NONCLUSTERED INDEX [_dta_index_T_OrderHistory_7_258099960__K10_K1_K2] ON [dbo].[T_OrderHistory]
(
	[OpenOrderID] ASC,
	[’Ê‰ÝƒyƒANo] ASC,
	[“úŽž] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
go
SET ANSI_PADDING ON
go
CREATE NONCLUSTERED INDEX [_dta_index_T_Trades_7_722101613__K23_1] ON [dbo].[T_Trades]
(
	[OpenOrderID] ASC
)
INCLUDE ( 	[TradeID]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
go
SET ANSI_PADDING ON
go
CREATE NONCLUSTERED INDEX [_dta_index_T_OrderHistory_7_258099960__K11] ON [dbo].[T_OrderHistory]
(
	[TradeID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]
go




