UPDATE [DemoA_FX].[hstr].tMonth1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tMonth1 as b
WHERE [DemoA_FX].[hstr].tMonth1.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tMonth1.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tWeek1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tWeek1 as b
WHERE [DemoA_FX].[hstr].tWeek1.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tWeek1.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tDay1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tDay1 as b
WHERE [DemoA_FX].[hstr].tDay1.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tDay1.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tHour1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tHour1 as b
WHERE [DemoA_FX].[hstr].tHour1.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tHour1.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tMin15
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tMin15 as b
WHERE [DemoA_FX].[hstr].tMin15.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tMin15.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tMin5
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tMin5 as b
WHERE [DemoA_FX].[hstr].tMin5.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tMin5.[StartDate] = b.[StartDate]
go

UPDATE [DemoA_FX].[hstr].tMin1
SET [買いSwap] = b.[買いSwap]
   ,[買いRate_始値] = b.[買いRate_始値]
   ,[買いRate_高値] = b.[買いRate_高値]
   ,[買いRate_安値] = b.[買いRate_安値]
   ,[買いRate_終値] = b.[買いRate_終値]
   ,[買いWMAs2] = b.[買いWMAs2]
   ,[買いWMAs2角度] = b.[買いWMAs2角度]
   ,[買いWMAs2角度シグマ] = b.[買いWMAs2角度シグマ]
   ,[買いWMAs2角度持続時間] = b.[買いWMAs2角度持続時間]
   ,[買いWMAs2角度持続Rate] = b.[買いWMAs2角度持続Rate]
   ,[買いWMAs14] = b.[買いWMAs14]
   ,[買いWMAs14角度] = b.[買いWMAs14角度]
   ,[買いWMAs14角度シグマ] = b.[買いWMAs14角度シグマ]
   ,[買いWMAs14角度持続時間] = b.[買いWMAs14角度持続時間]
   ,[買いWMAs14角度持続Rate] = b.[買いWMAs14角度持続Rate]
   ,[売りSwap] = b.[売りSwap]
   ,[売りRate_始値] = b.[売りRate_始値]
   ,[売りRate_高値] = b.[売りRate_高値]
   ,[売りRate_安値] = b.[売りRate_安値]
   ,[売りRate_終値] = b.[売りRate_終値]
   ,[売りWMAs2] = b.[売りWMAs2]
   ,[売りWMAs2角度] = b.[売りWMAs2角度]
   ,[売りWMAs2角度シグマ] = b.[売りWMAs2角度シグマ]
   ,[売りWMAs2角度持続時間] = b.[売りWMAs2角度持続時間]
   ,[売りWMAs2角度持続Rate] = b.[売りWMAs2角度持続Rate]
   ,[売りWMAs14] = b.[売りWMAs14]
   ,[売りWMAs14角度] = b.[売りWMAs14角度]
   ,[売りWMAs14角度シグマ] = b.[売りWMAs14角度シグマ]
   ,[売りWMAs14角度持続時間] = b.[売りWMAs14角度持続時間]
   ,[売りWMAs14角度持続Rate] = b.[売りWMAs14角度持続Rate]
   ,[登録日時] = b.[登録日時]
   ,[更新日時] = b.[更新日時]
FROM [RealA_FX].[hstr].tMin1 as b
WHERE [DemoA_FX].[hstr].tMin1.[通貨ペアNo] = b.[通貨ペアNo] AND [DemoA_FX].[hstr].tMin1.[StartDate] = b.[StartDate]
go
